// 20240220-ReactJS-PrimerProyecto/primer-proyecto/src/App.js
import './App.css';

import HeaderComponent from './components/header/HeaderComponent';
import MainComponent from './components/main/MainComponent';

function App() {
  return (
    <div className='container-fluid px-0'>
      <HeaderComponent/>
      <MainComponent/>
    </div>
  );
}

export default App;

// 20231220-Angular-Ecommerce/project-ecommerce/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'project-ecommerce';
}

<header class="container-fluid ">
  <app-header></app-header>
</header>

<main class="container">
  <app-main></app-main>
</main>
